language: node_js
node_js:
- '5'
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
  - bash install.sh
notifications:
  slack: devops-training-spb:PXr1hHRtdwqNmucS1mOYrn6a
deploy:
  app: radiant-ridge-22866
  provider: heroku
  api_key:
    secure: WR/344g3GSHsCnFh2Es/7A/wFMwKiOLz74h1hzmq5Ars+CbqTJwSe6TvqcpPsBKZMTo208/lCw1l4vcK28k+QB8c0N4qgdU53paZbL7EallvI5e/AApTYj3hSZkRPRlKfEyR4XGBcZxAn83IgSTXGSKzZCCvhYYmMZPvhkFpDXxL+cXj4qys1RE1VwgP3BTlsiOQ2gjN1xtCgnIC/anlNBcasETFtIlBHGCfIl5wIP95FyQ0rpq3IJfLRS34NFVW4kc3yfQQd0gP4iFUeqfm4yZGUlQCnupZUeRPbWqnhKb8jqvTTHBJuVDYEMTamfsnx99q32mGMTF03XKoCjo5SaUz9mnbTeGzCjCccwW+QrYuRdZhdVn80Fjve9hy+ABRqfNgrp28qpWiL/oh6tSvRvSFmBC2VRnO5BRfFfph4p/cxgCXEzzrUMSROQW05OzckIzkBuF3wuxRjtFSj20P8vkLt+bSvpeCtoZKxjckoHwweUJv1hSZxTDjVGWTYo8wPmzka04RdUcsgSmQnr+9pYajvYju7HR45yGClfREILmRYUplZ0livsR4jP7nerstONOsD9uqEue9AFMEYsUVaHDcRXGL9CdhA/1QXovbypA7ftg2r37J+o2NFKpo5qOMb8HFwMAxdQWRt98oq5Lm3Hnn3Q88T5c20CucWt5E+14=
